spring.application.name=zenoirprod
# Conexión universal usando localhost (Así nos funciona a todos con los parámetros por defecto de SQL Server y no hay que seguir tocando)
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=Zenoir_Prod;encrypt=true;trustServerCertificate=true;
spring.datasource.username=sa
spring.datasource.password=UFUchm4vP1cPz8BWbVy6
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Configuración de JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
